name: Update China IP List

on:
  schedule:
    # 每天凌晨3点运行 (UTC时间)
    - cron: '0 3 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run update script
      run: python scripts/update_cn_list.py
      
#    - name: Commit and push changes
#      uses: stefanzweifel/git-auto-commit-action@v5
#      with:
#        commit_message: 'Update'
#        file_pattern: cn_ip_list/CN

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add cn_ip_list/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update rules: $(date +'%Y-%m-%d %H:%M UTC+08:00')"
        git push
